// ── Score bar ─────────────────────────────────────────────────────────────────
function ScoreBar({ label, score }) {
  const color =
    score >= 60 ? '#00a86b' :
    score >= 40 ? '#d97706' :
    '#e53e3e'

  return (
    <div className="score-bar-wrap">
      <div className="score-bar-label-row">
        <span className="score-bar-label">{label}</span>
        <span className="score-bar-value" style={{ color }}>{score}%</span>
      </div>
      <div className="score-bar-track">
        <div
          className="score-bar-fill"
          style={{ width: `${score}%`, background: color }}
        />
      </div>
    </div>
  )
}

// ── Individual pick card ───────────────────────────────────────────────────────
function PickCard({ pick, isInWatchlist, onAdd, adding }) {
  const confidenceColor = {
    high:   '#00a86b',
    medium: '#d97706',
    low:    '#e53e3e',
  }[pick.confidence] ?? '#aaaaaa'

  return (
    <div className="pick-card">
      {/* Header row */}
      <div className="pick-card-top">
        <span className="pick-ticker">{pick.ticker}</span>
        <span
          className="pick-confidence"
          style={{ color: confidenceColor, borderColor: confidenceColor, background: `${confidenceColor}12` }}
        >
          {pick.confidence} confidence
        </span>
      </div>

      <p className="pick-name">{pick.name}</p>

      {/* Why now */}
      <p className="pick-why-now">{pick.whyNow}</p>

      {/* Score bars */}
      <div className="pick-scores">
        <ScoreBar label="20% gain in 1 year" score={pick.gain20in1yr} />
        <ScoreBar label="10%/yr over 5 years" score={pick.return10in5yr} />
      </div>

      {/* Pros */}
      <div className="pick-pros-cons">
        <p className="pick-pros-cons-heading pick-pros-heading">Pros</p>
        <ul className="pick-pros-cons-list">
          {pick.pros.map((p, i) => (
            <li key={i} className="pick-pro-item">
              <span className="pick-pro-icon">+</span>{p}
            </li>
          ))}
        </ul>
      </div>

      {/* Cons */}
      <div className="pick-pros-cons">
        <p className="pick-pros-cons-heading pick-cons-heading">Cons</p>
        <ul className="pick-pros-cons-list">
          {pick.cons.map((c, i) => (
            <li key={i} className="pick-con-item">
              <span className="pick-con-icon">−</span>{c}
            </li>
          ))}
        </ul>
      </div>

      {/* Add to watchlist */}
      <button
        className={`pick-add-btn ${isInWatchlist ? 'pick-add-btn-added' : ''}`}
        onClick={() => !isInWatchlist && onAdd(pick.ticker, pick.name)}
        disabled={isInWatchlist || adding}
      >
        {isInWatchlist ? '✓ In your watchlist' : adding ? 'Adding…' : '+ Add to watchlist'}
      </button>
    </div>
  )
}

// ── Main DailyPicks component ─────────────────────────────────────────────────
function DailyPicks({ picks, loading, error, fromCache, onRefresh, watchlist, onAddToWatchlist }) {
  const addingRef = {}  // track per-ticker loading state (not worth a useState)

  function formatDate(dateStr) {
    if (!dateStr) return ''
    const d = new Date(dateStr)
    return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })
  }

  return (
    <section className="daily-picks-section">

      {/* Section header */}
      <div className="daily-picks-header">
        <div className="daily-picks-title-group">
          <h2 className="daily-picks-title">
            <span className="daily-picks-title-accent">■</span> AI Daily Picks
          </h2>
          {picks && (
            <span className="daily-picks-date">{formatDate(picks.date)}</span>
          )}
        </div>
        <div className="daily-picks-header-right">
          {fromCache && <span className="cache-badge">Cached</span>}
          <button
            className="refresh-btn"
            onClick={onRefresh}
            disabled={loading}
          >
            {loading ? 'Analyzing…' : 'Refresh'}
          </button>
        </div>
      </div>

      {/* Disclaimer banner */}
      <div className="picks-disclaimer-banner">
        <span className="picks-disclaimer-icon">⚠</span>
        <span>
          <strong>Not financial advice.</strong> These picks are generated by AI from recent news headlines only —
          not from financial statements, earnings, or professional research.
          Scores are rough sentiment estimates, not predictions. Always do your own research before investing.
        </span>
      </div>

      {/* Loading */}
      {loading && (
        <div className="picks-loading">
          <div className="news-spinner" />
          <span>Claude is reading today's market headlines…</span>
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div className="picks-error">
          <p>{error}</p>
          <button onClick={onRefresh}>Try again</button>
        </div>
      )}

      {/* Picks grid */}
      {picks && !loading && (
        <>
          <div className="picks-grid">
            {picks.picks.map(pick => (
              <PickCard
                key={pick.ticker}
                pick={pick}
                isInWatchlist={watchlist.some(s => s.ticker === pick.ticker)}
                onAdd={onAddToWatchlist}
                adding={false}
              />
            ))}
          </div>

          {/* Footer */}
          <div className="picks-footer">
            <span>
              Based on {picks.newsCount || '50+'} headlines via Finnhub news aggregator
              (Reuters, MarketWatch, Yahoo Finance, Seeking Alpha, and more).
            </span>
            {picks.sourceSummary && (
              <span className="picks-mood"> Market mood: {picks.sourceSummary}</span>
            )}
          </div>
        </>
      )}
    </section>
  )
}

export default DailyPicks
